version: "3"
services:
 fedex_metaservice_v1:
    image: "fedex_metaservice:v1"
    container_name: "fedex-metaservice"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "2000M"
    env_file:
      - .env
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["uvicorn", "main:app","--host", "0.0.0.0", "--port", "8008"]
